services:
  - type: web
    name: zeno-bot
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
